AllCops:
  Include:
    - '**/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/LeadingEmptyLines:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
AmbiguousBlockAssociation:
  Enabled: false
