default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:postgres, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  host: <%= Rails.application.credentials.dig(:postgres, :host) %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :database) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :test_database) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :database) %>
  username: <%= Rails.application.credentials.dig(:postgres, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
