default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: human
  password: brain
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: human

test:
  <<: *default
  database: zombie

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :database) %>
  username: <%= Rails.application.credentials.dig(:postgres, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
